version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - echo "Building Java Lambda function..."
      - mvn clean install
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - cp target/ru-menu-scraper-3.1.3-aws.jar ru-menu-scraper.zip
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name ru-menu-scraper --zip-file fileb://ru-menu-scraper.zip --region sa-east-1
      - echo "Finished buildspec process"
