version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing Maven..."
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - echo "Building Java Lambda function..."
      - mvn clean install
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - cp target/ru-scraper-bot.jar ru-scraper-bot.zip
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name ru-scraper-bot --zip-file fileb://ru-scraper-bot.jar --region sa-east-1
      - echo "DONE!!"
